/* AUTO-GENERATED by scripts/extract-overworld-router.py — DO NOT EDIT */
#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* --- overworld.json 顶层 --- */
#define CHUNKUP_ROUTER_SEA_LEVEL           63
#define CHUNKUP_ROUTER_MIN_Y               -64
#define CHUNKUP_ROUTER_HEIGHT              384
#define CHUNKUP_ROUTER_SIZE_HORIZONTAL     1
#define CHUNKUP_ROUTER_SIZE_VERTICAL       2
#define CHUNKUP_ROUTER_CELL_WIDTH          (1u << (CHUNKUP_ROUTER_SIZE_HORIZONTAL + 1u))
#define CHUNKUP_ROUTER_CELL_HEIGHT         (1u << (CHUNKUP_ROUTER_SIZE_VERTICAL + 1u))

/* --- initial_density_without_jaggedness --- */
#define CHUNKUP_INIT_ADD1                  0.117188f
#define CHUNKUP_INIT_ADD2                  -0.117188f
#define CHUNKUP_INIT_ADD3                  -0.078125f
#define CHUNKUP_INIT_ADD4                  0.078125f
#define CHUNKUP_INIT_CORE_ADD              -0.703125f
#define CHUNKUP_INIT_CORE_MUL              4.000000f
#define CHUNKUP_INIT_CLAMP_MIN             -64.000000f
#define CHUNKUP_INIT_CLAMP_MAX             64.000000f

#define CHUNKUP_INIT_Y_BOTTOM_FROM_Y       -64
#define CHUNKUP_INIT_Y_BOTTOM_TO_Y         -40
#define CHUNKUP_INIT_Y_BOTTOM_FROM_V       0.000000f
#define CHUNKUP_INIT_Y_BOTTOM_TO_V         1.000000f

#define CHUNKUP_INIT_Y_TOP_FROM_Y          240
#define CHUNKUP_INIT_Y_TOP_TO_Y            256
#define CHUNKUP_INIT_Y_TOP_FROM_V          1.000000f
#define CHUNKUP_INIT_Y_TOP_TO_V            0.000000f

/* --- depth.json y_clamped_gradient --- */
#define CHUNKUP_DEPTH_Y_FROM_Y             -64
#define CHUNKUP_DEPTH_Y_TO_Y               320
#define CHUNKUP_DEPTH_Y_FROM_V             1.500000f
#define CHUNKUP_DEPTH_Y_TO_V               -1.500000f

#define CHUNKUP_SLOPED_CHEESE_MUL          4.000000f

/* --- base_3d_noise (old_blended_noise) --- */
#define CHUNKUP_BASE3D_XZ_SCALE            0.250000f
#define CHUNKUP_BASE3D_Y_SCALE             0.125000f
#define CHUNKUP_BASE3D_XZ_FACTOR           80.000000f
#define CHUNKUP_BASE3D_Y_FACTOR            160.000000f
#define CHUNKUP_BASE3D_SMEAR               8.000000f

/* --- shifted_noise xz_scale (continents/erosion/ridges) --- */
#define CHUNKUP_SHIFTED_XZ_SCALE           0.25f

/* --- aquifer router entries --- */
#define CHUNKUP_AQUIFER_BARRIER_XZ         1.000000f
#define CHUNKUP_AQUIFER_BARRIER_Y          0.500000f
#define CHUNKUP_AQUIFER_FLOODED_XZ         1.000000f
#define CHUNKUP_AQUIFER_FLOODED_Y          0.670000f
#define CHUNKUP_AQUIFER_SPREAD_XZ          1.000000f
#define CHUNKUP_AQUIFER_SPREAD_Y           0.714286f
#define CHUNKUP_AQUIFER_LAVA_XZ            1.000000f
#define CHUNKUP_AQUIFER_LAVA_Y             1.000000f
#define CHUNKUP_AQUIFER_LAVA_CUTOFF_Y      (-54)

static const float CHUNKUP_NOISE_CONTINENTALNESS_AMP[] = {
    1.000000f, 1.000000f, 2.000000f, 2.000000f, 2.000000f, 1.000000f, 1.000000f, 1.000000f,
    1.000000f,
};
#define CHUNKUP_NOISE_CONTINENTALNESS_AMP_LEN 9
#define CHUNKUP_NOISE_CONTINENTALNESS_FIRST -9

static const float CHUNKUP_NOISE_EROSION_AMP[] = {
    1.000000f, 1.000000f, 0.000000f, 1.000000f, 1.000000f,
};
#define CHUNKUP_NOISE_EROSION_AMP_LEN 5
#define CHUNKUP_NOISE_EROSION_FIRST        -9

static const float CHUNKUP_NOISE_RIDGE_AMP[] = {
    1.000000f, 2.000000f, 1.000000f, 0.000000f, 0.000000f, 0.000000f,
};
#define CHUNKUP_NOISE_RIDGE_AMP_LEN 6
#define CHUNKUP_NOISE_RIDGE_FIRST          -7

static const float CHUNKUP_SPLINE_OFFSET_CONTINENTS_LOC[] = {
    -1.100000f, -1.020000f, -0.510000f, -0.440000f, -0.180000f,
};
#define CHUNKUP_SPLINE_OFFSET_CONTINENTS_LOC_LEN 5
static const float CHUNKUP_SPLINE_OFFSET_CONTINENTS_VAL[] = {
    0.044000f, -0.222200f, -0.222200f, -0.120000f, -0.120000f,
};
#define CHUNKUP_SPLINE_OFFSET_CONTINENTS_VAL_LEN 5
#define CHUNKUP_SPLINE_OFFSET_CONTINENTS_COUNT 5

static const float CHUNKUP_SPLINE_FACTOR_CONTINENTS_LOC[] = {
    -0.190000f, -0.100000f, 0.030000f, 0.060000f, 0.350000f,
};
#define CHUNKUP_SPLINE_FACTOR_CONTINENTS_LOC_LEN 5
static const float CHUNKUP_SPLINE_FACTOR_CONTINENTS_VAL[] = {
    3.950000f, 5.470000f, 5.080000f, 4.690000f, 6.250000f,
};
#define CHUNKUP_SPLINE_FACTOR_CONTINENTS_VAL_LEN 5
#define CHUNKUP_SPLINE_FACTOR_CONTINENTS_COUNT 5

#ifdef __cplusplus
}
#endif
