#!/usr/bin/env python3
"""Generate OpenCL router sources from shared C headers (CPU/CUDA parity)."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMMON = ROOT / "native" / "common"
OUT = ROOT / "native" / "opencl" / "kernels" / "chunkup_router_codegen.clh"

HEADER_CHAIN = [
    COMMON / "chunkup_improved_noise.h",
    COMMON / "chunkup_normal_noise.h",
    COMMON / "chunkup_spline.h",
    COMMON / "chunkup_overworld_router.h",
    COMMON / "chunkup_factor_eval.h",
    COMMON / "chunkup_noise_bundle.h",
    COMMON / "chunkup_density_router.h",
]

# Minimal preamble: types and constants that must exist before shared headers.
PREAMBLE = """/* AUTO-GENERATED by scripts/codegen-opencl-router.py — DO NOT EDIT */
#pragma OPENCL EXTENSION cl_khr_fp64 : enable

#define CHUNKUP_CHUNK_SIZE 16u

typedef uchar uint8_t;
typedef uint uint32_t;

"""

# OpenCL kernel helpers — emitted after router/noise headers so forward refs resolve.
POSTAMBLE = """
#define CHUNKUP_CELL_W CHUNKUP_ROUTER_CELL_WIDTH
#define CHUNKUP_CELL_H CHUNKUP_ROUTER_CELL_HEIGHT

typedef struct ChunkupCellCache2D {
    ChunkupRouterSample2D samples[5][5];
} ChunkupCellCache2D;

inline int chunkup_cell_index_x(int lx) {
    return lx / (int)CHUNKUP_CELL_W;
}

inline int chunkup_cell_index_y(int ly) {
    return ly / (int)CHUNKUP_CELL_H;
}

inline float chunkup_cell_frac(int cell_local, int cell_size) {
    return (float)cell_local / (float)cell_size;
}

inline uint chunkup_block_index_cl(int lx, int ly, int lz, uint stride_y) {
    return (uint)ly * stride_y + (uint)lz * CHUNKUP_CHUNK_SIZE + (uint)lx;
}

inline float chunkup_cell_corner_density_cl(
    const __constant ChunkupNoiseBundle* bundle,
    const ChunkupCellCache2D* cache,
    int ci,
    int ck,
    int cj,
    int base_x,
    int base_z,
    int min_y
) {
    const float wx = (float)(base_x + ci * (int)CHUNKUP_CELL_W);
    const float wy = (float)(min_y + ck * (int)CHUNKUP_CELL_H);
    const float wz = (float)(base_z + cj * (int)CHUNKUP_CELL_W);
    const ChunkupRouterSample2D* s2d = &cache->samples[ci][cj];
    return chunkup_router_initial_density(bundle, s2d, wx, wy, wz);
}

inline float chunkup_cell_interpolated_density_cl(
    const __constant ChunkupNoiseBundle* bundle,
    const ChunkupCellCache2D* cache,
    int base_x,
    int base_z,
    int min_y,
    int lx,
    int ly,
    int lz
) {
    const int ci = chunkup_cell_index_x(lx);
    const int cj = chunkup_cell_index_x(lz);
    const int ck = chunkup_cell_index_y(ly);

    const float tx = chunkup_cell_frac(lx - ci * (int)CHUNKUP_CELL_W, (int)CHUNKUP_CELL_W);
    const float ty = chunkup_cell_frac(ly - ck * (int)CHUNKUP_CELL_H, (int)CHUNKUP_CELL_H);
    const float tz = chunkup_cell_frac(lz - cj * (int)CHUNKUP_CELL_W, (int)CHUNKUP_CELL_W);

    const float c000 = chunkup_cell_corner_density_cl(bundle, cache, ci, ck, cj, base_x, base_z, min_y);
    const float c100 = chunkup_cell_corner_density_cl(bundle, cache, ci + 1, ck, cj, base_x, base_z, min_y);
    const float c010 = chunkup_cell_corner_density_cl(bundle, cache, ci, ck + 1, cj, base_x, base_z, min_y);
    const float c110 = chunkup_cell_corner_density_cl(bundle, cache, ci + 1, ck + 1, cj, base_x, base_z, min_y);
    const float c001 = chunkup_cell_corner_density_cl(bundle, cache, ci, ck, cj + 1, base_x, base_z, min_y);
    const float c101 = chunkup_cell_corner_density_cl(bundle, cache, ci + 1, ck, cj + 1, base_x, base_z, min_y);
    const float c011 = chunkup_cell_corner_density_cl(bundle, cache, ci, ck + 1, cj + 1, base_x, base_z, min_y);
    const float c111 = chunkup_cell_corner_density_cl(bundle, cache, ci + 1, ck + 1, cj + 1, base_x, base_z, min_y);

    return chunkup_trilinear(tx, ty, tz, c000, c100, c010, c110, c001, c101, c011, c111);
}

"""


def strip_c_header(text: str) -> str:
    text = re.sub(r"/\* AUTO-GENERATED.*?\*/\s*", "", text, count=1)
    text = re.sub(r"#pragma once\s*", "", text)
    text = re.sub(r'#include\s+"[^"]+"\s*\n', "", text)
    text = re.sub(r"#include\s+<[^>]+>\s*\n", "", text)
    text = re.sub(r"#ifdef __cplusplus\s*", "", text)
    text = re.sub(r"extern \"C\" \{\s*", "", text)
    text = re.sub(r"#endif\s*//.*?__cplusplus.*?\n", "", text)
    text = re.sub(r"\s*#endif\s*", "\n", text)
    text = re.sub(r"\n}\s*$", "", text.rstrip()) + "\n"
    text = text.replace("CHUNKUP_FN", "inline")
    text = text.replace("CHUNKUP_ARRAY", "constant")
    text = text.replace("fabsf(", "fabs(")
    text = text.replace("floorf(", "floor(")
    text = text.replace("const float*", "const __constant float*")
    text = text.replace("const ChunkupNoiseBundle*", "const __constant ChunkupNoiseBundle*")
    text = text.replace("const ChunkupNoiseTables*", "const __constant ChunkupNoiseTables*")
    return text


def main() -> int:
    parts = [PREAMBLE]
    for path in HEADER_CHAIN:
        if not path.is_file():
            print(f"missing header: {path}", file=sys.stderr)
            return 1
        parts.append(f"/* --- {path.name} --- */\n")
        parts.append(strip_c_header(path.read_text(encoding="utf-8")))
        parts.append("\n")

    parts.append(POSTAMBLE)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
