#!/usr/bin/env python3
"""从 factor.json 生成嵌套 spline 求值器（continents → erosion → ridges / ridges_folded）。"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXTRACTED = ROOT / "build" / "extracted" / "data" / "minecraft" / "worldgen"
OUT = ROOT / "native" / "common" / "chunkup_factor_eval.h"


def fmt_float(v: float) -> str:
    return f"{v:.6f}f"


class SplineCodegen:
    def __init__(self) -> None:
        self.nodes: list[dict] = []
        self.cache: dict[str, int] = {}

    def _key(self, node: dict) -> str:
        return json.dumps(node, sort_keys=True)

    def register(self, node: dict) -> int:
        key = self._key(node)
        if key in self.cache:
            return self.cache[key]
        idx = len(self.nodes)
        self.nodes.append(node)
        self.cache[key] = idx
        return idx

    def parse_spline(self, spline: dict) -> int:
        points = []
        for pt in spline.get("points", []):
            loc = float(pt["location"])
            val = pt["value"]
            if isinstance(val, (int, float)):
                points.append({"loc": loc, "scalar": float(val), "child": None})
            elif isinstance(val, dict) and "points" in val:
                child = self.parse_spline(val)
                points.append({"loc": loc, "scalar": None, "child": child})
            else:
                points.append({"loc": loc, "scalar": 0.0, "child": None})
        return self.register({"type": "spline", "coordinate": spline.get("coordinate", ""), "points": points})

    def emit_eval_fn(self, idx: int) -> str:
        node = self.nodes[idx]
        name = f"chunkup_factor_node_{idx}"
        if node["type"] != "spline":
            return name

        points = node["points"]
        locs = [p["loc"] for p in points]
        lines = [
            f"CHUNKUP_FN float {name}(float x, float erosion, float ridges, float ridges_folded) {{",
            f"    const float loc[] = {{{', '.join(fmt_float(v) for v in locs)}}};",
            f"    const int count = {len(points)};",
        ]

        val_refs = []
        for i, pt in enumerate(points):
            if pt["child"] is not None:
                child_name = f"chunkup_factor_node_{pt['child']}"
                axis = self.nodes[pt["child"]].get("coordinate", "")
                if "ridges_folded" in axis:
                    arg = "ridges_folded"
                elif "ridges" in axis:
                    arg = "ridges"
                elif "erosion" in axis:
                    arg = "erosion"
                else:
                    arg = "x"
                lines.append(f"    const float v{i} = {child_name}({arg}, erosion, ridges, ridges_folded);")
            else:
                lines.append(f"    const float v{i} = {fmt_float(pt['scalar'])};")
            val_refs.append(f"v{i}")

        lines.append(f"    const float val[] = {{{', '.join(val_refs)}}};")
        lines.append("    if (count <= 1) return val[0];")
        lines.append("    if (x <= loc[0]) return val[0];")
        lines.append("    if (x >= loc[count - 1]) return val[count - 1];")
        lines.append("    for (int i = 0; i < count - 1; ++i) {")
        lines.append("        if (x >= loc[i] && x <= loc[i + 1]) {")
        lines.append("            const float span = loc[i + 1] - loc[i];")
        lines.append("            if (span <= 1e-6f) return val[i + 1];")
        lines.append("            const float t = (x - loc[i]) / span;")
        lines.append("            return val[i] + (val[i + 1] - val[i]) * t;")
        lines.append("        }")
        lines.append("    }")
        lines.append("    return val[count - 1];")
        lines.append("}")
        return "\n".join(lines)

    def emit_all(self) -> str:
        parts = [
            "/* AUTO-GENERATED by scripts/codegen-factor-spline.py — DO NOT EDIT */",
            "#pragma once",
            '#include "chunkup_compat.h"',
            '#include "chunkup_spline.h"',
            "",
            "#ifdef __cplusplus",
            'extern "C" {',
            "#endif",
            "",
        ]
        for idx in range(len(self.nodes)):
            parts.append(self.emit_eval_fn(idx))
            parts.append("")
        root = len(self.nodes) - 1
        parts.extend(
            [
                "/** factor.json 顶层（blend_alpha=1 时即为 factor）。 */",
                "CHUNKUP_FN float chunkup_factor_eval(",
                "    float continents,",
                "    float erosion,",
                "    float ridges,",
                "    float ridges_folded",
                ") {",
                f"    return chunkup_factor_node_{root}(continents, erosion, ridges, ridges_folded);",
                "}",
                "",
                "#ifdef __cplusplus",
                "}",
                "#endif",
            ]
        )
        return "\n".join(parts)


def find_factor_root_spline(factor: dict) -> dict:
    node = factor
    for _ in range(12):
        if isinstance(node, dict) and node.get("type") == "minecraft:spline" and "spline" in node:
            return node["spline"]
        if isinstance(node, dict) and "argument2" in node:
            node = node["argument2"]
            continue
        if isinstance(node, dict) and "argument1" in node:
            node = node["argument1"]
            continue
        if isinstance(node, dict) and "argument" in node:
            node = node["argument"]
            continue
        break
    raise ValueError("could not locate factor root spline")


def main() -> int:
    factor_path = EXTRACTED / "density_function/overworld/factor.json"
    if not factor_path.exists():
        if OUT.exists():
            print(f"skipping factor codegen — {OUT} exists")
            return 0
        raise FileNotFoundError(factor_path)

    factor = json.loads(factor_path.read_text(encoding="utf-8"))
    root = find_factor_root_spline(factor)
    gen = SplineCodegen()
    gen.parse_spline(root)
    header = gen.emit_all()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header, encoding="utf-8")
    print(f"wrote {OUT} ({len(header)} bytes, {len(gen.nodes)} spline nodes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
