#!/usr/bin/env python3
"""从 Minecraft 1.20.1 overworld.json 提取 noise_router 系数，生成 C 头文件。"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXTRACTED = ROOT / "build" / "extracted" / "data" / "minecraft" / "worldgen"
OUT = ROOT / "native" / "common" / "chunkup_overworld_router.h"


def load_json(rel: str) -> dict:
    path = EXTRACTED / rel
    if not path.exists():
        raise FileNotFoundError(f"missing {path} — run jar extract first")
    return json.loads(path.read_text(encoding="utf-8"))


def flatten_scalar_spline(node: dict, out: list[tuple[float, float]]) -> None:
    """提取 spline 中 value 为标量的控制点 (location, value)。"""
    if "points" not in node:
        return
    for pt in node["points"]:
        loc = float(pt["location"])
        val = pt["value"]
        if isinstance(val, (int, float)):
            out.append((loc, float(val)))


def dedupe_sorted(points: list[tuple[float, float]]) -> list[tuple[float, float]]:
    by_loc: dict[float, float] = {}
    for loc, val in points:
        by_loc[loc] = val
    return sorted(by_loc.items())


def fmt_float(v: float) -> str:
    return f"{v:.6f}f"


def fmt_float_array(name: str, values: list[float], per_line: int = 8) -> str:
    lines = [f"CHUNKUP_ARRAY float {name}[] = {{"]
    for i in range(0, len(values), per_line):
        chunk = ", ".join(fmt_float(v) for v in values[i : i + per_line])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append(f"#define {name}_LEN {len(values)}")
    return "\n".join(lines)


def fmt_spline_array(name: str, points: list[tuple[float, float]]) -> str:
    locs = [p[0] for p in points]
    vals = [p[1] for p in points]
    return (
        fmt_float_array(f"{name}_LOC", locs)
        + "\n"
        + fmt_float_array(f"{name}_VAL", vals)
        + f"\n#define {name}_COUNT {len(points)}"
    )


def main() -> int:
    overworld = load_json("noise_settings/overworld.json")
    depth = load_json("density_function/overworld/depth.json")
    offset = load_json("density_function/overworld/offset.json")
    factor = load_json("density_function/overworld/factor.json")
    sloped = load_json("density_function/overworld/sloped_cheese.json")
    base3d = load_json("density_function/overworld/base_3d_noise.json")
    continentalness = load_json("noise/continentalness.json")
    erosion_noise = load_json("noise/erosion.json")
    ridge_noise = load_json("noise/ridge.json")

    router = overworld["noise_router"]
    init = router["initial_density_without_jaggedness"]
    noise_cfg = overworld["noise"]

    # initial_density_without_jaggedness 顶层系数
    init_add1 = float(init["argument1"])
    mul_outer = init["argument2"]
    y_bottom = mul_outer["argument1"]
    add_mid = mul_outer["argument2"]
    init_add2 = float(add_mid["argument1"])
    add_inner = add_mid["argument2"]
    init_add3 = float(add_inner["argument1"])
    mul_top = add_inner["argument2"]
    y_top = mul_top["argument1"]
    init_add4 = float(mul_top["argument2"]["argument1"])
    clamp_node = mul_top["argument2"]["argument2"]
    init_core_add = float(clamp_node["input"]["argument1"])
    init_core_mul = float(clamp_node["input"]["argument2"]["argument1"])
    init_clamp_min = float(clamp_node["min"])
    init_clamp_max = float(clamp_node["max"])

    depth_y = depth["argument1"]
    sloped_mul = float(sloped["argument1"]["argument1"])

    # continents → offset / factor 标量 spline 控制点
    offset_pts: list[tuple[float, float]] = []
    factor_pts: list[tuple[float, float]] = []
    flatten_scalar_spline(
        offset["argument"]["argument"]["argument2"]["argument1"]["argument2"]["spline"],
        offset_pts,
    )
    flatten_scalar_spline(
        factor["argument"]["argument"]["argument2"]["argument2"]["argument2"]["spline"],
        factor_pts,
    )
    offset_pts = dedupe_sorted(offset_pts)
    factor_pts = dedupe_sorted(factor_pts)
    # factor.json 大量嵌套 spline，补充关键标量控制点
    factor_fallback = [
        (-0.19, 3.95),
        (-0.10, 5.47),
        (0.03, 5.08),
        (0.06, 4.69),
        (0.35, 6.25),
    ]
    factor_pts = dedupe_sorted(factor_pts + factor_fallback)

    # aquifer noise scales
    barrier = router["barrier"]
    flooded = router["fluid_level_floodedness"]
    spread = router["fluid_level_spread"]
    lava = router["lava"]

    header = f"""/* AUTO-GENERATED by scripts/extract-overworld-router.py — DO NOT EDIT */
#pragma once

#include "chunkup_compat.h"
#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* --- overworld.json 顶层 --- */
#define CHUNKUP_ROUTER_SEA_LEVEL           {overworld['sea_level']}
#define CHUNKUP_ROUTER_MIN_Y               {noise_cfg['min_y']}
#define CHUNKUP_ROUTER_HEIGHT              {noise_cfg['height']}
#define CHUNKUP_ROUTER_SIZE_HORIZONTAL     {noise_cfg['size_horizontal']}
#define CHUNKUP_ROUTER_SIZE_VERTICAL       {noise_cfg['size_vertical']}
#define CHUNKUP_ROUTER_CELL_WIDTH          (1u << (CHUNKUP_ROUTER_SIZE_HORIZONTAL + 1u))
#define CHUNKUP_ROUTER_CELL_HEIGHT         (1u << (CHUNKUP_ROUTER_SIZE_VERTICAL + 1u))

/* --- initial_density_without_jaggedness --- */
#define CHUNKUP_INIT_ADD1                  {fmt_float(init_add1)}
#define CHUNKUP_INIT_ADD2                  {fmt_float(init_add2)}
#define CHUNKUP_INIT_ADD3                  {fmt_float(init_add3)}
#define CHUNKUP_INIT_ADD4                  {fmt_float(init_add4)}
#define CHUNKUP_INIT_CORE_ADD              {fmt_float(init_core_add)}
#define CHUNKUP_INIT_CORE_MUL              {fmt_float(init_core_mul)}
#define CHUNKUP_INIT_CLAMP_MIN             {fmt_float(init_clamp_min)}
#define CHUNKUP_INIT_CLAMP_MAX             {fmt_float(init_clamp_max)}

#define CHUNKUP_INIT_Y_BOTTOM_FROM_Y       {y_bottom['from_y']}
#define CHUNKUP_INIT_Y_BOTTOM_TO_Y         {y_bottom['to_y']}
#define CHUNKUP_INIT_Y_BOTTOM_FROM_V       {fmt_float(float(y_bottom['from_value']))}
#define CHUNKUP_INIT_Y_BOTTOM_TO_V         {fmt_float(float(y_bottom['to_value']))}

#define CHUNKUP_INIT_Y_TOP_FROM_Y          {y_top['from_y']}
#define CHUNKUP_INIT_Y_TOP_TO_Y            {y_top['to_y']}
#define CHUNKUP_INIT_Y_TOP_FROM_V          {fmt_float(float(y_top['from_value']))}
#define CHUNKUP_INIT_Y_TOP_TO_V            {fmt_float(float(y_top['to_value']))}

/* --- depth.json y_clamped_gradient --- */
#define CHUNKUP_DEPTH_Y_FROM_Y             {depth_y['from_y']}
#define CHUNKUP_DEPTH_Y_TO_Y               {depth_y['to_y']}
#define CHUNKUP_DEPTH_Y_FROM_V             {fmt_float(float(depth_y['from_value']))}
#define CHUNKUP_DEPTH_Y_TO_V               {fmt_float(float(depth_y['to_value']))}

#define CHUNKUP_SLOPED_CHEESE_MUL          {fmt_float(sloped_mul)}

/* --- base_3d_noise (old_blended_noise) --- */
#define CHUNKUP_BASE3D_XZ_SCALE            {fmt_float(float(base3d['xz_scale']))}
#define CHUNKUP_BASE3D_Y_SCALE             {fmt_float(float(base3d['y_scale']))}
#define CHUNKUP_BASE3D_XZ_FACTOR           {fmt_float(float(base3d['xz_factor']))}
#define CHUNKUP_BASE3D_Y_FACTOR            {fmt_float(float(base3d['y_factor']))}
#define CHUNKUP_BASE3D_SMEAR               {fmt_float(float(base3d['smear_scale_multiplier']))}

/* --- shifted_noise xz_scale (continents/erosion/ridges) --- */
#define CHUNKUP_SHIFTED_XZ_SCALE           0.25f

/* --- aquifer router entries --- */
#define CHUNKUP_AQUIFER_BARRIER_XZ         {fmt_float(float(barrier['xz_scale']))}
#define CHUNKUP_AQUIFER_BARRIER_Y          {fmt_float(float(barrier['y_scale']))}
#define CHUNKUP_AQUIFER_FLOODED_XZ         {fmt_float(float(flooded['xz_scale']))}
#define CHUNKUP_AQUIFER_FLOODED_Y          {fmt_float(float(flooded['y_scale']))}
#define CHUNKUP_AQUIFER_SPREAD_XZ          {fmt_float(float(spread['xz_scale']))}
#define CHUNKUP_AQUIFER_SPREAD_Y           {fmt_float(float(spread['y_scale']))}
#define CHUNKUP_AQUIFER_LAVA_XZ            {fmt_float(float(lava['xz_scale']))}
#define CHUNKUP_AQUIFER_LAVA_Y             {fmt_float(float(lava['y_scale']))}
#define CHUNKUP_AQUIFER_LAVA_CUTOFF_Y      (-54)

{fmt_float_array('CHUNKUP_NOISE_CONTINENTALNESS_AMP', [float(x) for x in continentalness['amplitudes']])}
#define CHUNKUP_NOISE_CONTINENTALNESS_FIRST {continentalness['firstOctave']}

{fmt_float_array('CHUNKUP_NOISE_EROSION_AMP', [float(x) for x in erosion_noise['amplitudes']])}
#define CHUNKUP_NOISE_EROSION_FIRST        {erosion_noise['firstOctave']}

{fmt_float_array('CHUNKUP_NOISE_RIDGE_AMP', [float(x) for x in ridge_noise['amplitudes']])}
#define CHUNKUP_NOISE_RIDGE_FIRST          {ridge_noise['firstOctave']}

{fmt_spline_array('CHUNKUP_SPLINE_OFFSET_CONTINENTS', offset_pts)}

{fmt_spline_array('CHUNKUP_SPLINE_FACTOR_CONTINENTS', factor_pts)}

#ifdef __cplusplus
}}
#endif
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header, encoding="utf-8")
    print(f"wrote {OUT} ({len(header)} bytes)")
    print(f"  offset spline points: {len(offset_pts)}")
    print(f"  factor spline points: {len(factor_pts)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
